apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfgsee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfgsee
  template:
    metadata:
      labels:
        app: dfgsee
    spec:
      containers:
      - image: okteto.dev/dfgsee:latest
        name: dfgsee
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "cbaca50b-9511-4ed0-8d49-687a4131e73f"
        - name: Vless_Path
          value: "/vl5df55"
        - name: Vmess_UUID
          value: "cbaca50b-9511-4ed0-8d49-687a4131e73f"
        - name: Vmess_Path
          value: "/vm66dfs6"
        - name: Share_Path
          value: "/v2link"
